variable "identifier" {}
variable "engine_version" {}
variable "instance_type" {}
variable "storage_size" {}
variable "db_name" {}
variable "username" {}
variable "password" {}
variable "port" {}
variable "multi_az" {}
variable "publicly_accessible" {}
variable "vpc_security_group_ids" {}
